# Generated by Django 3.2.20 on 2023-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_clientprofile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Address'),
        ),
    ]
