# Generated by Django 4.2.3 on 2023-08-02 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_productdetail_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success')], default='Pending', max_length=10, verbose_name='Status')),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Total Amount')),
                ('payment_method', models.CharField(max_length=10, verbose_name='Payment Method')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='main.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productdetail', verbose_name='Product')),
            ],
        ),
    ]
