# Generated by Django 4.2.3 on 2023-08-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_alter_productdetail_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_detail',
        ),
    ]
