# Generated by Django 3.2.20 on 2023-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stockmovement_processed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Address'),
        ),
    ]
