# Generated by Django 3.2.20 on 2023-08-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Payment ID'),
        ),
    ]
