# Generated by Django 3.2.20 on 2023-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0, verbose_name='Total Amount (Frw)'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity (m)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price (Frw)'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity (m)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Quantity (m)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='Total Price (Frw)'),
        ),
    ]
